# Generated by Django 4.1.7 on 2023-03-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_choice',
            field=models.CharField(choices=[('U', 'UPVOTE'), ('D', 'DOWNVOTE')], max_length=1),
        ),
    ]
