# Generated by Django 4.1.7 on 2023-04-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_activity_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
