# Generated by Django 4.1.7 on 2023-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_beer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
