# Generated by Django 4.1.7 on 2023-04-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_beer_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='likes',
        ),
    ]
