# Generated by Django 4.1.7 on 2023-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_tag_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
