# Generated by Django 4.1.7 on 2023-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tag_downvote_count_tag_upvote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
