# Generated by Django 4.1.7 on 2023-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_beer_downvote_count_beer_upvote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
    ]
